server:
  node_id: storage-node-4
  hostname: 0.0.0.0
  port: 8081
  shard_id: shard-2
  replica_id: 1
gossip:
  port: 7946
  seeds:
    - "storage-1:7946"
lsm:
  data_dir: /data/storage-node-4
  fsync: true
logger:
  level: "info"
  encoding: "json"
